dist: xenial
language: java
sudo: false
install: gradle wrapper --gradle-version=6.8.2 && ./gradlew assemble
script: ./gradlew clean build war
jdk:
  - openjdk8
  - openjdk11
  # Oracle JDK 8 is broken on Xenial.
  # - oraclejdk8
  - oraclejdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
